### ISSUE TITLE
Codecov badge shows coverage unknown

### ISSUE THREAD

**Issue by feldoh** [kgryte/shields-badge-url-codecov#1]
The codecov badge in the README.md shows coverage:unknown. On [codecov](https://codecov.io/github/kgryte/shields-badge-url-codecov?branch=master) it says: "Unable to retrieve commit from GitHub API. Please check that your bot user has authorization to kgryte/shields-badge-url-codecov." I can make a pr if you'd like it done by travis push instead of by git hook?

**Comment by kgryte** [comment]
@feldoh I am not sure what happened. Not sure if `codecov` changed an API endpoint, or GitHub did, or something else. I have been seeing the `unknown` status on quite a few repos and I am not sure why, as all these badges were showing the correct status when initially written and published.

**Comment by kgryte** [comment]
Apparently, `codecov` needs access to private repos. Updated account settings and now the link above no longer has the bot message, but the badge still has not updated to show the coverage.

**Comment by kgryte** [comment]
Reran the build. Badge now shows coverage. Closing.

**Comment by ghost** [comment]
The badge displays "unknown" for [this](https://github.com/saurabmish/Advanced-Algorithms) public repository. 

Travis CI build shows "passing". I've added `codecov` in `.travis.yml`.

How do I make sure that "coverage" is displayed?
